# Generated by Django 3.2.4 on 2021-06-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='banner',
            field=models.ImageField(blank=True, upload_to='banners/'),
        ),
    ]
